# Generated by Django 3.1.7 on 2021-03-06 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_carrega_ufs_municipios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuário'},
        ),
        migrations.RenameField(
            model_name='pacientedoenca',
            old_name='tempo_diagostico',
            new_name='tempo_diagnostico',
        ),
        migrations.AlterField(
            model_name='doenca',
            name='cid',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
