# Generated by Django 3.1.7 on 2021-03-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_preenche_doencas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pacientedoenca',
            options={'verbose_name': 'Doença do Paciente', 'verbose_name_plural': 'Doenças do Paciente'},
        ),
        migrations.RenameField(
            model_name='pacientedoenca',
            old_name='doencas',
            new_name='doenca',
        ),
        migrations.RenameField(
            model_name='pacientedoenca',
            old_name='pacientes',
            new_name='paciente',
        ),
        migrations.AlterField(
            model_name='pacientedoenca',
            name='tempo_diagnostico',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tempo de Diagnóstico'),
        ),
    ]
