# Generated by Django 3.1.7 on 2021-03-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20210309_1916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doenca',
            options={'ordering': ('nome',), 'verbose_name': 'Doença'},
        ),
        migrations.AlterModelOptions(
            name='medico',
            options={'verbose_name': 'Médico'},
        ),
        migrations.AlterField(
            model_name='user',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nome_mae',
            field=models.CharField(max_length=80, verbose_name='Nome da Mãe'),
        ),
    ]
